### ISSUE TITLE
 Where I enter the data from firebase

### ISSUE THREAD

**Issue by newmesiss** [mugan86/angularjs-firebase-push-to-android#1]
I see that with this project I can send messages to my devices, but where do I configure the data delivered by firebase?
As the key and application name

**Comment by mugan86** [comment]
Good afternoon,
I did importing from a Google project (from when using Google Cloud Messaging) but if you do from 0 in Firebase you have to follow this reference: https://firebase.google.com/docs/android/setup

If you start with a project from 0 in firebase (first believe it) you go to Notifications, select "Android" and there you will be asked for three data, the package name (required), app name (optional) and your signature certificate SHA-1 debugging (optional).

To continue clicking "Add application" and you will be given the instructions, to download the file "google-services.json" to place it in your Android project, give you to continue and further steps on how to configure the project.

Once you have this (you already have the application), to get the API Key, go to the top left and click on the icon of the "wheel" and select "Project Settings" and inside it "messaging in the cloud "Where you will find the KEY API with the name" Server Key "inside the" project credentials ".

I have explained a little above but I think that following the reference of the official documentation you will have it although I have done those steps and I think they are enough to make it work.

Regards!

**Comment by mugan86** [comment]
Also in the README file you have all the necessary instructions, is what I have explained in the end.

**Comment by newmesiss** [comment]
Thanks for the answer, I do a project in ionic and I have notifications running, now probe this project sullo but I do not get the notifications to my device, enter my apikey of firebase in the file message.php, which more I must add in that archive?
Usually other platforms ask for the ap name as "com.myapp.name"

**Comment by mugan86** [comment]
With Ionic I have worked with the pushwoosh service but never with firebase. If you give me 2-3 days I try it and I'll tell you okay? That right now to respond to something without knowing 100% sure, I prefer to tell you that I have no idea but with Ionic if I work and could look at it. Here is an example that runs the server with node and sends messages through GCM: http://devgirl.org/2013/07/17/tutorial-implement-push-notifications-in-your-phonegap-application/

**Comment by newmesiss** [comment]
Perfect thanks, I implement my notifications with this plugin since the ionic documentation recommend it, it has worked very well for me but now I am looking for the server side to send, although from the frebase console it is very good but I need to outsource it.
https://github.com/fechanique/cordova-plugin-fcm

**Comment by mugan86** [comment]
@newmesiss OK. I already created the example in Ionic V1 with the plugin that you mentioned to me and I have shaped a bit the part of the file message.php with respect to the skeleton of the message. You have to change the name of the package in config.xml and put yours and then generate the file google-services.json. I close the bug because it really was not, I was just prepared for an implementation of mine and not for that particular plugin whose author has left very well explained as it has to be the skeleton of the message. It has only been adapting that and trying it several times.
Source: https://github.com/mugan86/ionic-push-example-with-fcm
